name = "FOAM"
uuid = "faef0fd8-a221-49a6-a29f-831367e0b889"
authors = ["himcraft"]
version = "0.0.5"

[deps]
GZip = "92fee26a-97fe-5a0c-ad85-20a5f3185b63"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
